import{a as h,i as l,S as B}from"./assets/vendor-Dy2ZTtfi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();h.defaults.baseURL="https://pixabay.com/api/";const M="50743656-f34c73b2fc7295c80e7e7c3d4";let f=1;const $=15;let m="";async function g(e,r=1){try{return(await h.get("",{params:{key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:$}})).data}catch(n){throw l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),n}}function O(e){e!==m&&(m=e,f=1)}function y(){return f}function L(){f+=1}const E=new B(".gallery a",{captionsData:"alt",captionDelay:250}),b=document.querySelector(".gallery");function w(e){const r=e.map(({webformatURL:n,largeImageURL:c,tags:t,likes:o,views:s,comments:P,downloads:S})=>`
        <li class="gallery-item">
          <a href="${c}">
            <img src="${n}" alt="${t}" />
          </a>
          <div class="info">
            <p>Likes: <span>${o}</span></p>
            <p>Views: <span>${s}</span></p>
            <p>Comments: <span>${P}</span></p>
            <p>Downloads: <span>${S}</span></p>
          </div>
        </li>
      `).join("");b.insertAdjacentHTML("beforeend",r),E.refresh()}function R(){b.innerHTML=""}function q(){const e=document.querySelector(".loader");e.classList.remove("hidden"),requestAnimationFrame(()=>{e.classList.add("show")})}function p(){const e=document.querySelector(".loader");e.classList.remove("show"),setTimeout(()=>{e.classList.add("hidden")},400)}function x(){document.querySelector(".load-btn").classList.remove("hidden")}function i(){document.querySelector(".load-btn").classList.add("hidden")}let a="",v=0,d=0;const u=document.querySelector(".form"),C=document.querySelector(".load-btn");i();u.addEventListener("submit",async e=>{if(e.preventDefault(),R(),i(),q(),a=e.currentTarget.elements["search-text"].value.trim(),!a){l.error({title:"Warning",message:"Please enter a search term",position:"topRight",backgroundColor:"orange"}),u.reset(),p();return}O(a),d=0;try{const r=await g(a,y());if(v=r.totalHits,r.hits.length===0){l.info({title:"Oops",message:"No images found",position:"topRight"}),i();return}w(r.hits),d=r.hits.length,x(),L()}catch(r){console.error(r)}finally{p(),u.reset()}});C.addEventListener("click",async()=>{q();try{const e=await g(a,y());if(e.hits.length===0){i();return}w(e.hits),d+=e.hits.length;const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),d>=v&&(i(),l.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),L()}catch(e){console.error(e)}finally{p()}});
//# sourceMappingURL=index.js.map
