import{a as m,i as a,S as M}from"./assets/vendor-Dy2ZTtfi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();m.defaults.baseURL="https://pixabay.com/api/";const $="50743656-f34c73b2fc7295c80e7e7c3d4";let h=1;const E=15;let g="";async function y(e,r=1){try{return(await m.get("",{params:{key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:E}})).data}catch(n){throw a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),n}}function O(e){e!==g&&(g=e,h=1)}function L(){return h}function b(){h+=1}const R=new M(".gallery a",{captionsData:"alt",captionDelay:250}),v=document.querySelector(".gallery");function P(e){const r=e.map(({webformatURL:n,largeImageURL:l,tags:t,likes:o,views:s,comments:w,downloads:B})=>`
        <li class="gallery-item">
          <a href="${l}">
            <img src="${n}" alt="${t}" />
          </a>
          <div class="info">
            <p>Likes: <span>${o}</span></p>
            <p>Views: <span>${s}</span></p>
            <p>Comments: <span>${w}</span></p>
            <p>Downloads: <span>${B}</span></p>
          </div>
        </li>
      `).join("");v.insertAdjacentHTML("beforeend",r),R.refresh()}function x(){v.innerHTML=""}function S(){document.querySelector(".loader").classList.remove("hidden")}function p(){document.querySelector(".loader").classList.add("hidden")}function q(){document.querySelector(".load-btn").classList.remove("hidden")}function c(){document.querySelector(".load-btn").classList.add("hidden")}let d="",f=0,i=0;const u=document.querySelector(".form"),C=document.querySelector(".load-btn");c();u.addEventListener("submit",async e=>{if(e.preventDefault(),x(),S(),c(),d=e.currentTarget.elements["search-text"].value.trim(),!d){a.error({title:"Warning",message:"Please enter a search term",position:"topRight",backgroundColor:"orange"}),u.reset(),p();return}O(),i=0;try{const r=await y(d,L());if(f=r.totalHits,r.hits.length===0){a.info({title:"Oops",message:"No images found",position:"topRight"});return}P(r.hits),i=r.hits.length,i<f?q():(c(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),b()}catch(r){console.error(r)}finally{p(),u.reset()}});C.addEventListener("click",async()=>{S();try{const e=await y(d,L());if(e.hits.length===0){c();return}P(e.hits),i+=e.hits.length;const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),i<f?q():(c(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),b()}catch(e){console.error(e)}finally{p()}});
//# sourceMappingURL=index.js.map
