import{a as m,i as l,S as v}from"./assets/vendor-Dy2ZTtfi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();m.defaults.baseURL="https://pixabay.com/api/";const S="50743656-f34c73b2fc7295c80e7e7c3d4",M=15;async function h(e,r=1){try{return(await m.get("",{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:M}})).data}catch(s){throw l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),s}}const P=new v(".gallery a",{captionsData:"alt",captionDelay:250}),g=document.querySelector(".gallery");function y(e){const r=e.map(({webformatURL:s,largeImageURL:i,tags:t,likes:o,views:n,comments:w,downloads:q})=>`
        <li class="gallery-item">
          <a href="${i}">
            <img src="${s}" alt="${t}" />
          </a>
          <div class="info">
            <p>Likes: <span>${o}</span></p>
            <p>Views: <span>${n}</span></p>
            <p>Comments: <span>${w}</span></p>
            <p>Downloads: <span>${q}</span></p>
          </div>
        </li>
      `).join("");g.insertAdjacentHTML("beforeend",r),P.refresh()}function B(){g.innerHTML=""}function L(){const e=document.querySelector(".loader");e.classList.remove("hidden"),requestAnimationFrame(()=>{e.classList.add("show")})}function f(){const e=document.querySelector(".loader");e.classList.remove("show"),setTimeout(()=>{e.classList.add("hidden")},400)}function O(){document.querySelector(".load-btn").classList.remove("hidden")}function d(){document.querySelector(".load-btn").classList.add("hidden")}let a=1,c="",b=0,u=0;const p=document.querySelector(".form"),$=document.querySelector(".load-btn");d();p.addEventListener("submit",async e=>{if(e.preventDefault(),B(),L(),c=e.currentTarget.elements["search-text"].value.trim(),!c){l.error({title:"Warning",message:"Please enter a search term",position:"topRight",backgroundColor:"orange"}),p.reset(),f();return}a=1,u=0;try{const r=await h(c,a);if(b=r.totalHits,r.hits.length===0){l.info({title:"Oops",message:"No images found",position:"topRight"}),d();return}y(r.hits),u=r.hits.length,O(),a++}catch(r){console.error(r)}finally{f(),p.reset()}});$.addEventListener("click",async()=>{L();try{const e=await h(c,a);if(e.hits.length===0){d();return}y(e.hits),u+=e.hits.length,u>=b&&(d(),l.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),a++}catch(e){console.error(e)}finally{f()}});
//# sourceMappingURL=index.js.map
